### ISSUE TITLE
fail2web newbie inquiry

### ISSUE THREAD

**Issue by ItsAdventureTime** [Sean-Der/fail2web#26]
Hi,

I am looking forward of installing fail2web on my Debian 7 x64 server. Still a newbie here and I have no idea how to. Another thing, I wanna use the latest unreleased version of fail2ban, not the one from a distro since the latest one has a lot of new features.

Thanks.

**Comment by Sean-Der** [comment]
Closing from inactivity, feel free to reopen @ItsAdventureTime 

thanks!
