### ISSUE TITLE
Error after build

### ISSUE THREAD

**Issue by sheo13666** [Sean-Der/fail2web#28]
bundle.js:423 Uncaught TypeError: undefined is not a function

**Comment by Sean-Der** [comment]
Hey @sheo13666 

Did you see any errors while running the build?

Also, the bundle.js is checked into version control. So if you are not making any changes to fail2web, you should be able to just use that one.

thanks!

**Comment by Sean-Der** [comment]
Closing from inactivity, feel free to reopen @sheo13666 

thanks!
