### ISSUE TITLE
Installation link seems to be dead

### ISSUE THREAD

**Issue by polytan02** [Sean-Der/fail2web#30]
Hi,

In the installing section of the readme, the link https://www.phillmoore.com/9-programming/7-setting-up-fail2web-with-apache seems to be dead.

Do you know where to find the doc to install your web interface please ?

**Comment by djengineerllc** [comment]
That's my bad, I'm working on moving over to a new site.  I need to get the new installation documentation back.  I should have it back w/in a couple weeks tops.  Hopefully I finish it this weekend. :)

**Comment by Sean-Der** [comment]
@djengineerllc thanks for getting on this so quickly!

I can still get your Apache and nginx setup guide via Google's cache, but the styling is messed up :( 

Want me to mirror your instructions, until you get them back up on your blog (or would you prefer I leave the link for the time being?)

**Comment by djengineerllc** [comment]
If you can mirror the instructions that'd be great.  Sorry about that Sean!  I'm switching from an Apache/MySQL/Joomla site to a Nginx/MongoDB/Ghost site instead.

**Comment by Sean-Der** [comment]
Closed by 7938300d65512a8e42b1bb7526455d338e38aed5

@djengineerllc I couldn't find all your guides in the Google Cache :( if you have them saved somewhere I would love to host them on the GitHub wiki and link to them as well!
