### ISSUE TITLE
problem with front page

### ISSUE THREAD

**Issue by cyberrock** [Sean-Der/fail2web#32]
Hi 
I have just installed as per the install manual. though the webpage doesnt work. i get a message on the top left side of the page "Unparseable error when attempting to contact fail2rest"

**Comment by Sean-Der** [comment]
Hi @cyberrock!
Sorry for the delay, started a new job.

What version of fail2ban and fail2rest are you running? Also, what does `curl http://127.0.0.1:5000/global/status` return, if you are using the default fail2rest config?

thanks!

**Comment by mgaulton** [comment]
Hi There @Sean-Der, 

I'm getting the same message as @cyberrock  Using a fresh install of fail2web, fail2rest with default configs along with fail2ban 0.9.3 on Apache Opensuse.

curl http://127.0.0.1:5000/global/status result is:
["apache-auth","apache-badbots","apache-botsearch","apache-clientdenied","apache-fakegooglebot","apache-modsecurity","apache-nohome","apache-nokiddies","apache-nokiddies2","apache-noscript","apache-overflows","apache-postflood","apache-shellshock","apache-shellshock2","apache-sqlinject","apache-webmail-phish","apache-wootwoot","artillery","fail2ban","http-get-dos","pam-generic","php-url-fopen","postfix-rbl","sendmail-auth","sendmail-reject","squid","sshd","sshd-ddos","webmin-auth","wordpress-login","wordpress-xmlrpc"]Y



Apache log:
[Thu Feb 25 12:42:28.479537 2016] [proxy:warn] [pid 3864] [client 129.97.244.52:51788] AH01144: No protocol handler was valid for the URL /api/global/status. If you are using a DSO version of mod_proxy, make
 sure the proxy submodules are included in the configuration using LoadModule., referer: http://sb.silverdragons.net/

**Comment by mgaulton** [comment]
So while i thought i had them loaded, i had to load the below to make the magic happen.

sudo a2enmod proxy
sudo a2enmod proxy_balancer
sudo a2enmod proxy_http

**Comment by cyberrock** [comment]
Sorry for the delay, ended up having some big problems requiring a centos re-install... any way, just tried to install it all again... same problem. but i think it stems from rest not installing properly.  Following your guide lines, it just hangs on  sudo -E go run *.go

**Comment by cyberrock** [comment]
disregard.... just figured it out.... it should be go run *.go & or add it to start on start up

**Comment by Sean-Der** [comment]
Great to hear! Sorry for the delay @cyberrock
