### ISSUE TITLE
Invalid pickle version after dist-upgrade from Debian 9 -> 10 -> 11

### ISSUE THREAD

**Issue by mbautista** [Sean-Der/fail2web#41]
Hello,
Thank you for this great app :)

We just upgraded some old servers from Debian 9 up to Debian 11 with fail2web installed.
service fail2rest is active (running)

But the fail2web interface displays the following error : 
invalid pickle version

It seems to be related to the python version, but not sure...
Could anyone please help us to solve this problem ?

Thank you very much :)
Mathieu.

**Comment by mbautista** [comment]
I have the following but unfortunately it does not work : 
```
# Try to upgrade fail2rest
cd /opt/go/src/github.com/Sean-Der/fail2rest
go get -u all
service fail2rest restart

# Try to upgrade og-rek, see https://github.com/kisielk/og-rek/commit/8def3d024dac365b755fbf5dfe373352caa1a5a9
cd /opt/go/src/github.com/kisielk/og-rek
go get -u all
service fail2rest restart
```
I am not very familiar with go, could anyone please help ?
Thank you very much :)

**Comment by mbautista** [comment]
Hello,
I managed to upgrade fail2rest with the og-rek module with the following command : 
```
cd /opt/go
GOPATH=/opt/go/ go install -v github.com/Sean-Der/fail2rest
systemctl daemon-reload
service fail2rest restart
```
Now now fail2web displays the jail list, but I have the following error when I click on a jail : 
```
502 Bad Gateway - Couldn't contact fail2rest 
```
When I open the web inspector, the URLs with the 502 errors are for example : 
```
https://myserver/fail2web/api/jail/postfix
https://myserver/fail2web/api/jail/dovecot
...
```

**Comment by mbautista** [comment]
Hello,
Fail2web is now working on Debian 11 after applying the following commands : 
```
# Step 1 : remove golang debian package as it is too old
apt remove golang*

# Step 2 : download and install latest golang
cd /opt
wget https://go.dev/dl/go1.22.4.linux-amd64.tar.gz
tar -zxvf go1.22.4.linux-amd64.tar.gz 
ln -s /opt/go/bin/go /usr/bin/go

# Step 3 : Install muriloventuroso/fail2rest@latest
GOPATH=/opt/go go install github.com/muriloventuroso/fail2rest@latest
rm /etc/systemd/system/fail2rest.service
ln -s /opt/go/pkg/mod/github.com/muriloventuroso/fail2rest\@v0.0.0-20220928134531-a7d8777b1f83/init-scripts/systemd /etc/systemd/system/fail2rest.service
systemctl daemon-reload
service fail2rest stop
service fail2rest start
```

**Comment by Sean-Der** [comment]
Hey @mbautista can you try with `v1.0.1` of this repo?

I just added Go modules to `fail2go` and `fail2rest` and cherry-picked some commits :)
